image_width: 640
image_height: 480
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [607.95733,   0.     , 310.2277 ,
           0.     , 610.47417, 236.96966,
           0.     ,   0.     ,   1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.038667, 0.059763, 0.002976, -0.002525, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [604.97076,   0.     , 308.30925,   0.     ,
           0.     , 607.56506, 237.69204,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]
